### ISSUE TITLE
redux的使用有些疑问

### ISSUE THREAD

**Issue by su6838354** [bailicangdu/react-pxq#15]
reducer里面的内容基本没太大作用，本来是希望接受action 和必要参数后，构建new state的；
比如下面这段应该放到reducer中
                list.forEach((item,index)=>{
                    // FIXME: 这里修改state 正确吗
                    this.state.productList[index] = {};
                    this.state.productList[index]['productName'] = item.product_name;
                    this.state.productList[index]['chooseState'] = false;
                    this.state.productList[index]['id'] = item.product_id;
                    this.state.productList[index]['num'] = 1;
}))

我觉得接受到action+参数product_id, num 等，在reducer中构建吧

**Comment by bailicangdu** [comment]
这样写是因为我要改变state的值但是又不想出发更新。
