### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by KevinYY** [bailicangdu/react-pxq#18]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch        okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@        1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"        })

**Comment by VanillaSkyLove** [comment]
me too！

**Comment by zentoLu** [comment]
windows下就会有这个问题，mac不会

**Comment by whatlife** [comment]
@zentoLu 楼上的方法并不是真正的解决办法。如果我要用sass呢？

可以这么办： node-sass的版本号改成3.4.2，然后cnpm install
或者直接 cnpm install，换阿里的源来安装。我就是这么做的。

网络上也有其他办法：
http://react-china.org/t/node-sass/3872
https://github.com/luqin/blog/issues/9

**Comment by yaowen2011** [comment]
也遇到这个错了
我试了  npm install --force 也是可以的
