### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by yxuecheng** [bailicangdu/react-pxq#23]
server.js 属于node中间层吗？

**Comment by bailicangdu** [comment]
server.js 是开启本地服务器的，底层是调用nodejs原生的http模块

**Comment by yxuecheng** [comment]
@bailicangdu server_hot 引入了express 也不属于中间层？

**Comment by bailicangdu** [comment]
express 是nodejs框架，封装了nodejs的一些方法，这些都是属于nodejs的知识了
