### ISSUE TITLE
亲哥,抽空重构下吧

### ISSUE THREAD

**Issue by imshgga** [bailicangdu/react-pxq#69]
能提意见不...3559star的项目,不能丢份呀.我想你现在看这代码,估计也很纠结了,哈哈.想看看react的代码,学习下最佳实践,就看了个components/index.jsx,然后...就看不下去了.
随便说两句吧.你把方法都写在了constructor中,这样的话,这些是实例方法,不是原型方法,每次new的时候,都会来一遍,很浪费性能的...代码风格也不统一呀,字符串操作还是用``的好,好看也好写.有些事件,你没用箭头函数,没bind(this),我赶脚是要出问题滴...不说了
别杀我...我什么都不知道

**Comment by bailicangdu** [comment]
哈哈，其实已经开始做了，因为公司项目忙所以暂停了，元旦抽空重构一下。一年前的项目，的确技术和方法都过时了，重构的时候会用最新的技术
