### ISSUE TITLE
npm start报错

### ISSUE THREAD

**Issue by First-blood** [bailicangdu/react-pxq#74]
Failed to compile
./src/pages/home/home.jsx
Module not found: `/Users/gatakemasa/Documents/react-pxq/src/config/config.js` does not match the corresponding path on disk `Config.js`.
This error occurred during the build time and cannot be dismissed.

**Comment by bailicangdu** [comment]
有中文路径？

**Comment by canfoo** [comment]
![image](https://user-images.githubusercontent.com/16999086/35212297-9f39829a-ff94-11e7-9098-f87972a0981e.png)
字母大小写写错了。
