### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by walkinMrwang** [bailicangdu/react-pxq#75]
[
![qtz3kvkhij0g 0f 214 p u](https://user-images.githubusercontent.com/26135370/34977145-6377879e-fad4-11e7-8817-a1f664d94f20.png)
](url)

**Comment by gyt95** [comment]
+1

**Comment by yushaoyi** [comment]
package.json 修改，前面加个node就可以
<pre>
 "scripts": {
    "start": "node bin/react-scripts start",
    "build": "node bin/react-scripts build",
    "test": "node bin/react-scripts test --env=jsdom",
    "eject": "node bin/react-scripts eject"
  }
</pre>

**Comment by bailicangdu** [comment]
运行入口文件已修改

**Comment by packaaa** [comment]
是 npm run start
