### ISSUE TITLE
import API from '@/api/api';

### ISSUE THREAD

**Issue by MarryJia** [bailicangdu/react-pxq#77]
import API from '@/api/api'; 报找不到对象  使用@ 需要安装什么插件吗？我用的是webstorm  我改成 ../就没有问题了，

**Comment by bailicangdu** [comment]
@是webpack声明的别称，绝对路径，指向src文件夹

**Comment by hnlylmlzh** [comment]
@mixin({padStr})
这里的@ 是什么意思呢

**Comment by bailicangdu** [comment]
修饰器

**Comment by dadazhouRenee** [comment]
为什么我写@mixin 的时候会报 ‘Support for the experimental syntax 'decorators-legacy' isn't currently enabled’ 这个错呀
