### ISSUE TITLE
npm run build 以后在pxq文件夹里启动http-server报错

### ISSUE THREAD

**Issue by ChengZhengHao** [bailicangdu/react-pxq#78]
![image](https://user-images.githubusercontent.com/12841025/35087341-d6699016-fc6a-11e7-8955-3f2c599657c8.png)

提示路径不对

**Comment by bailicangdu** [comment]
在上层目录启动

**Comment by czh7867480** [comment]
![image](https://user-images.githubusercontent.com/12841025/35130722-54d29848-fcfd-11e7-9203-2eeaf01e7553.png)
谢谢老兄回复，在上层目录启动依旧不太对
