### ISSUE TITLE
请问scripts文件的配置是引自哪个项目的，我看到github上好几个人也用这个配置

### ISSUE THREAD

**Issue by herechc** [bailicangdu/react-pxq#79]

**Comment by bailicangdu** [comment]
create-react-app 脚手架的

**Comment by herechc** [comment]
@bailicangdu 请问你安装完create-react-app是执行npm run eject吗，为什么我eject后package文件跟你的不一样，安装的都是在dependencies里面的，scripts也只有build.js,start.js,test.js三个文件

**Comment by xiaoweibaniu** [comment]
@herechc 作者按照自己的需求修改了配置
