### ISSUE TITLE
页面自适应没解决？

### ISSUE THREAD

**Issue by lyorribery** [bailicangdu/react-pxq#89]
如题

**Comment by annie-** [comment]
你说的是什么自适应没解决？

**Comment by lyorribery** [comment]
![tim 20180508135159](https://user-images.githubusercontent.com/33805194/39740256-7045319c-52c7-11e8-8e82-e7c5fe6c7c0d.png)
chrome打开的效果

**Comment by DanceSmile** [comment]
这是哪里有问题么  我怎么没看出来 挺好的啊
